package com.jyinfo.jy_domain.Entity.mybatisEntity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DevelopConsultEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_develop_consult
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_develop_consult
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_develop_consult
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_develop_consult
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    public DevelopConsultEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_develop_consult
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_develop_consult
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_develop_consult
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_develop_consult
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_develop_consult
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_develop_consult
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_develop_consult
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_develop_consult
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_develop_consult
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_develop_consult
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_develop_consult
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFConsultIdIsNull() {
            addCriterion("F_Consult_ID is null");
            return (Criteria) this;
        }

        public Criteria andFConsultIdIsNotNull() {
            addCriterion("F_Consult_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFConsultIdEqualTo(Integer value) {
            addCriterion("F_Consult_ID =", value, "fConsultId");
            return (Criteria) this;
        }

        public Criteria andFConsultIdNotEqualTo(Integer value) {
            addCriterion("F_Consult_ID <>", value, "fConsultId");
            return (Criteria) this;
        }

        public Criteria andFConsultIdGreaterThan(Integer value) {
            addCriterion("F_Consult_ID >", value, "fConsultId");
            return (Criteria) this;
        }

        public Criteria andFConsultIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("F_Consult_ID >=", value, "fConsultId");
            return (Criteria) this;
        }

        public Criteria andFConsultIdLessThan(Integer value) {
            addCriterion("F_Consult_ID <", value, "fConsultId");
            return (Criteria) this;
        }

        public Criteria andFConsultIdLessThanOrEqualTo(Integer value) {
            addCriterion("F_Consult_ID <=", value, "fConsultId");
            return (Criteria) this;
        }

        public Criteria andFConsultIdIn(List<Integer> values) {
            addCriterion("F_Consult_ID in", values, "fConsultId");
            return (Criteria) this;
        }

        public Criteria andFConsultIdNotIn(List<Integer> values) {
            addCriterion("F_Consult_ID not in", values, "fConsultId");
            return (Criteria) this;
        }

        public Criteria andFConsultIdBetween(Integer value1, Integer value2) {
            addCriterion("F_Consult_ID between", value1, value2, "fConsultId");
            return (Criteria) this;
        }

        public Criteria andFConsultIdNotBetween(Integer value1, Integer value2) {
            addCriterion("F_Consult_ID not between", value1, value2, "fConsultId");
            return (Criteria) this;
        }

        public Criteria andFNameIsNull() {
            addCriterion("F_Name is null");
            return (Criteria) this;
        }

        public Criteria andFNameIsNotNull() {
            addCriterion("F_Name is not null");
            return (Criteria) this;
        }

        public Criteria andFNameEqualTo(String value) {
            addCriterion("F_Name =", value, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameNotEqualTo(String value) {
            addCriterion("F_Name <>", value, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameGreaterThan(String value) {
            addCriterion("F_Name >", value, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameGreaterThanOrEqualTo(String value) {
            addCriterion("F_Name >=", value, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameLessThan(String value) {
            addCriterion("F_Name <", value, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameLessThanOrEqualTo(String value) {
            addCriterion("F_Name <=", value, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameLike(String value) {
            addCriterion("F_Name like", value, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameNotLike(String value) {
            addCriterion("F_Name not like", value, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameIn(List<String> values) {
            addCriterion("F_Name in", values, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameNotIn(List<String> values) {
            addCriterion("F_Name not in", values, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameBetween(String value1, String value2) {
            addCriterion("F_Name between", value1, value2, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameNotBetween(String value1, String value2) {
            addCriterion("F_Name not between", value1, value2, "fName");
            return (Criteria) this;
        }

        public Criteria andFMobileIsNull() {
            addCriterion("F_Mobile is null");
            return (Criteria) this;
        }

        public Criteria andFMobileIsNotNull() {
            addCriterion("F_Mobile is not null");
            return (Criteria) this;
        }

        public Criteria andFMobileEqualTo(String value) {
            addCriterion("F_Mobile =", value, "fMobile");
            return (Criteria) this;
        }

        public Criteria andFMobileNotEqualTo(String value) {
            addCriterion("F_Mobile <>", value, "fMobile");
            return (Criteria) this;
        }

        public Criteria andFMobileGreaterThan(String value) {
            addCriterion("F_Mobile >", value, "fMobile");
            return (Criteria) this;
        }

        public Criteria andFMobileGreaterThanOrEqualTo(String value) {
            addCriterion("F_Mobile >=", value, "fMobile");
            return (Criteria) this;
        }

        public Criteria andFMobileLessThan(String value) {
            addCriterion("F_Mobile <", value, "fMobile");
            return (Criteria) this;
        }

        public Criteria andFMobileLessThanOrEqualTo(String value) {
            addCriterion("F_Mobile <=", value, "fMobile");
            return (Criteria) this;
        }

        public Criteria andFMobileLike(String value) {
            addCriterion("F_Mobile like", value, "fMobile");
            return (Criteria) this;
        }

        public Criteria andFMobileNotLike(String value) {
            addCriterion("F_Mobile not like", value, "fMobile");
            return (Criteria) this;
        }

        public Criteria andFMobileIn(List<String> values) {
            addCriterion("F_Mobile in", values, "fMobile");
            return (Criteria) this;
        }

        public Criteria andFMobileNotIn(List<String> values) {
            addCriterion("F_Mobile not in", values, "fMobile");
            return (Criteria) this;
        }

        public Criteria andFMobileBetween(String value1, String value2) {
            addCriterion("F_Mobile between", value1, value2, "fMobile");
            return (Criteria) this;
        }

        public Criteria andFMobileNotBetween(String value1, String value2) {
            addCriterion("F_Mobile not between", value1, value2, "fMobile");
            return (Criteria) this;
        }

        public Criteria andFUnitIsNull() {
            addCriterion("F_Unit is null");
            return (Criteria) this;
        }

        public Criteria andFUnitIsNotNull() {
            addCriterion("F_Unit is not null");
            return (Criteria) this;
        }

        public Criteria andFUnitEqualTo(String value) {
            addCriterion("F_Unit =", value, "fUnit");
            return (Criteria) this;
        }

        public Criteria andFUnitNotEqualTo(String value) {
            addCriterion("F_Unit <>", value, "fUnit");
            return (Criteria) this;
        }

        public Criteria andFUnitGreaterThan(String value) {
            addCriterion("F_Unit >", value, "fUnit");
            return (Criteria) this;
        }

        public Criteria andFUnitGreaterThanOrEqualTo(String value) {
            addCriterion("F_Unit >=", value, "fUnit");
            return (Criteria) this;
        }

        public Criteria andFUnitLessThan(String value) {
            addCriterion("F_Unit <", value, "fUnit");
            return (Criteria) this;
        }

        public Criteria andFUnitLessThanOrEqualTo(String value) {
            addCriterion("F_Unit <=", value, "fUnit");
            return (Criteria) this;
        }

        public Criteria andFUnitLike(String value) {
            addCriterion("F_Unit like", value, "fUnit");
            return (Criteria) this;
        }

        public Criteria andFUnitNotLike(String value) {
            addCriterion("F_Unit not like", value, "fUnit");
            return (Criteria) this;
        }

        public Criteria andFUnitIn(List<String> values) {
            addCriterion("F_Unit in", values, "fUnit");
            return (Criteria) this;
        }

        public Criteria andFUnitNotIn(List<String> values) {
            addCriterion("F_Unit not in", values, "fUnit");
            return (Criteria) this;
        }

        public Criteria andFUnitBetween(String value1, String value2) {
            addCriterion("F_Unit between", value1, value2, "fUnit");
            return (Criteria) this;
        }

        public Criteria andFUnitNotBetween(String value1, String value2) {
            addCriterion("F_Unit not between", value1, value2, "fUnit");
            return (Criteria) this;
        }

        public Criteria andFBudgetIsNull() {
            addCriterion("F_Budget is null");
            return (Criteria) this;
        }

        public Criteria andFBudgetIsNotNull() {
            addCriterion("F_Budget is not null");
            return (Criteria) this;
        }

        public Criteria andFBudgetEqualTo(String value) {
            addCriterion("F_Budget =", value, "fBudget");
            return (Criteria) this;
        }

        public Criteria andFBudgetNotEqualTo(String value) {
            addCriterion("F_Budget <>", value, "fBudget");
            return (Criteria) this;
        }

        public Criteria andFBudgetGreaterThan(String value) {
            addCriterion("F_Budget >", value, "fBudget");
            return (Criteria) this;
        }

        public Criteria andFBudgetGreaterThanOrEqualTo(String value) {
            addCriterion("F_Budget >=", value, "fBudget");
            return (Criteria) this;
        }

        public Criteria andFBudgetLessThan(String value) {
            addCriterion("F_Budget <", value, "fBudget");
            return (Criteria) this;
        }

        public Criteria andFBudgetLessThanOrEqualTo(String value) {
            addCriterion("F_Budget <=", value, "fBudget");
            return (Criteria) this;
        }

        public Criteria andFBudgetLike(String value) {
            addCriterion("F_Budget like", value, "fBudget");
            return (Criteria) this;
        }

        public Criteria andFBudgetNotLike(String value) {
            addCriterion("F_Budget not like", value, "fBudget");
            return (Criteria) this;
        }

        public Criteria andFBudgetIn(List<String> values) {
            addCriterion("F_Budget in", values, "fBudget");
            return (Criteria) this;
        }

        public Criteria andFBudgetNotIn(List<String> values) {
            addCriterion("F_Budget not in", values, "fBudget");
            return (Criteria) this;
        }

        public Criteria andFBudgetBetween(String value1, String value2) {
            addCriterion("F_Budget between", value1, value2, "fBudget");
            return (Criteria) this;
        }

        public Criteria andFBudgetNotBetween(String value1, String value2) {
            addCriterion("F_Budget not between", value1, value2, "fBudget");
            return (Criteria) this;
        }

        public Criteria andFDescriptionIsNull() {
            addCriterion("F_Description is null");
            return (Criteria) this;
        }

        public Criteria andFDescriptionIsNotNull() {
            addCriterion("F_Description is not null");
            return (Criteria) this;
        }

        public Criteria andFDescriptionEqualTo(String value) {
            addCriterion("F_Description =", value, "fDescription");
            return (Criteria) this;
        }

        public Criteria andFDescriptionNotEqualTo(String value) {
            addCriterion("F_Description <>", value, "fDescription");
            return (Criteria) this;
        }

        public Criteria andFDescriptionGreaterThan(String value) {
            addCriterion("F_Description >", value, "fDescription");
            return (Criteria) this;
        }

        public Criteria andFDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("F_Description >=", value, "fDescription");
            return (Criteria) this;
        }

        public Criteria andFDescriptionLessThan(String value) {
            addCriterion("F_Description <", value, "fDescription");
            return (Criteria) this;
        }

        public Criteria andFDescriptionLessThanOrEqualTo(String value) {
            addCriterion("F_Description <=", value, "fDescription");
            return (Criteria) this;
        }

        public Criteria andFDescriptionLike(String value) {
            addCriterion("F_Description like", value, "fDescription");
            return (Criteria) this;
        }

        public Criteria andFDescriptionNotLike(String value) {
            addCriterion("F_Description not like", value, "fDescription");
            return (Criteria) this;
        }

        public Criteria andFDescriptionIn(List<String> values) {
            addCriterion("F_Description in", values, "fDescription");
            return (Criteria) this;
        }

        public Criteria andFDescriptionNotIn(List<String> values) {
            addCriterion("F_Description not in", values, "fDescription");
            return (Criteria) this;
        }

        public Criteria andFDescriptionBetween(String value1, String value2) {
            addCriterion("F_Description between", value1, value2, "fDescription");
            return (Criteria) this;
        }

        public Criteria andFDescriptionNotBetween(String value1, String value2) {
            addCriterion("F_Description not between", value1, value2, "fDescription");
            return (Criteria) this;
        }

        public Criteria andFCreateTimeIsNull() {
            addCriterion("F_Create_Time is null");
            return (Criteria) this;
        }

        public Criteria andFCreateTimeIsNotNull() {
            addCriterion("F_Create_Time is not null");
            return (Criteria) this;
        }

        public Criteria andFCreateTimeEqualTo(Date value) {
            addCriterion("F_Create_Time =", value, "fCreateTime");
            return (Criteria) this;
        }

        public Criteria andFCreateTimeNotEqualTo(Date value) {
            addCriterion("F_Create_Time <>", value, "fCreateTime");
            return (Criteria) this;
        }

        public Criteria andFCreateTimeGreaterThan(Date value) {
            addCriterion("F_Create_Time >", value, "fCreateTime");
            return (Criteria) this;
        }

        public Criteria andFCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("F_Create_Time >=", value, "fCreateTime");
            return (Criteria) this;
        }

        public Criteria andFCreateTimeLessThan(Date value) {
            addCriterion("F_Create_Time <", value, "fCreateTime");
            return (Criteria) this;
        }

        public Criteria andFCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("F_Create_Time <=", value, "fCreateTime");
            return (Criteria) this;
        }

        public Criteria andFCreateTimeIn(List<Date> values) {
            addCriterion("F_Create_Time in", values, "fCreateTime");
            return (Criteria) this;
        }

        public Criteria andFCreateTimeNotIn(List<Date> values) {
            addCriterion("F_Create_Time not in", values, "fCreateTime");
            return (Criteria) this;
        }

        public Criteria andFCreateTimeBetween(Date value1, Date value2) {
            addCriterion("F_Create_Time between", value1, value2, "fCreateTime");
            return (Criteria) this;
        }

        public Criteria andFCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("F_Create_Time not between", value1, value2, "fCreateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_develop_consult
     *
     * @mbggenerated do_not_delete_during_merge Thu Sep 10 01:08:19 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_develop_consult
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}