package com.jyinfo.jy_domain.Entity.mybatisEntity;

import java.util.Date;

public class DevelopConsultEntity  {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_develop_consult.F_Consult_ID
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    private Integer fConsultId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_develop_consult.F_Name
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    private String fName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_develop_consult.F_Mobile
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    private String fMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_develop_consult.F_Unit
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    private String fUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_develop_consult.F_Budget
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    private String fBudget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_develop_consult.F_Description
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    private String fDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_develop_consult.F_Create_Time
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    private Date fCreateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_develop_consult.F_Consult_ID
     *
     * @return the value of t_develop_consult.F_Consult_ID
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    public Integer getfConsultId() {
        return fConsultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_develop_consult.F_Consult_ID
     *
     * @param fConsultId the value for t_develop_consult.F_Consult_ID
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    public void setfConsultId(Integer fConsultId) {
        this.fConsultId = fConsultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_develop_consult.F_Name
     *
     * @return the value of t_develop_consult.F_Name
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    public String getfName() {
        return fName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_develop_consult.F_Name
     *
     * @param fName the value for t_develop_consult.F_Name
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    public void setfName(String fName) {
        this.fName = fName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_develop_consult.F_Mobile
     *
     * @return the value of t_develop_consult.F_Mobile
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    public String getfMobile() {
        return fMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_develop_consult.F_Mobile
     *
     * @param fMobile the value for t_develop_consult.F_Mobile
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    public void setfMobile(String fMobile) {
        this.fMobile = fMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_develop_consult.F_Unit
     *
     * @return the value of t_develop_consult.F_Unit
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    public String getfUnit() {
        return fUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_develop_consult.F_Unit
     *
     * @param fUnit the value for t_develop_consult.F_Unit
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    public void setfUnit(String fUnit) {
        this.fUnit = fUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_develop_consult.F_Budget
     *
     * @return the value of t_develop_consult.F_Budget
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    public String getfBudget() {
        return fBudget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_develop_consult.F_Budget
     *
     * @param fBudget the value for t_develop_consult.F_Budget
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    public void setfBudget(String fBudget) {
        this.fBudget = fBudget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_develop_consult.F_Description
     *
     * @return the value of t_develop_consult.F_Description
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    public String getfDescription() {
        return fDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_develop_consult.F_Description
     *
     * @param fDescription the value for t_develop_consult.F_Description
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    public void setfDescription(String fDescription) {
        this.fDescription = fDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_develop_consult.F_Create_Time
     *
     * @return the value of t_develop_consult.F_Create_Time
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    public Date getfCreateTime() {
        return fCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_develop_consult.F_Create_Time
     *
     * @param fCreateTime the value for t_develop_consult.F_Create_Time
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    public void setfCreateTime(Date fCreateTime) {
        this.fCreateTime = fCreateTime;
    }

    @Override
    public String toString() {
        return "DevelopConsultEntity{" +
                "fConsultId=" + fConsultId +
                ", fName='" + fName + '\'' +
                ", fMobile='" + fMobile + '\'' +
                ", fUnit='" + fUnit + '\'' +
                ", fBudget='" + fBudget + '\'' +
                ", fDescription='" + fDescription + '\'' +
                ", fCreateTime=" + fCreateTime +
                '}';
    }
}