package com.jyinfo.jy_domain.Entity.mybatisEntity;

import java.util.Date;

public class LoginLogEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_login_log.F_Log_Id
     *
     * @mbggenerated Mon Sep 14 15:06:50 CST 2020
     */
    private Integer fLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_login_log.F_User_ID
     *
     * @mbggenerated Mon Sep 14 15:06:50 CST 2020
     */
    private Integer fUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_login_log.F_Login_Time
     *
     * @mbggenerated Mon Sep 14 15:06:50 CST 2020
     */
    private Date fLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_login_log.F_Ip_Address
     *
     * @mbggenerated Mon Sep 14 15:06:50 CST 2020
     */
    private String fIpAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_login_log.F_Log_Id
     *
     * @return the value of f_login_log.F_Log_Id
     *
     * @mbggenerated Mon Sep 14 15:06:50 CST 2020
     */
    public Integer getfLogId() {
        return fLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_login_log.F_Log_Id
     *
     * @param fLogId the value for f_login_log.F_Log_Id
     *
     * @mbggenerated Mon Sep 14 15:06:50 CST 2020
     */
    public void setfLogId(Integer fLogId) {
        this.fLogId = fLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_login_log.F_User_ID
     *
     * @return the value of f_login_log.F_User_ID
     *
     * @mbggenerated Mon Sep 14 15:06:50 CST 2020
     */
    public Integer getfUserId() {
        return fUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_login_log.F_User_ID
     *
     * @param fUserId the value for f_login_log.F_User_ID
     *
     * @mbggenerated Mon Sep 14 15:06:50 CST 2020
     */
    public void setfUserId(Integer fUserId) {
        this.fUserId = fUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_login_log.F_Login_Time
     *
     * @return the value of f_login_log.F_Login_Time
     *
     * @mbggenerated Mon Sep 14 15:06:50 CST 2020
     */
    public Date getfLoginTime() {
        return fLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_login_log.F_Login_Time
     *
     * @param fLoginTime the value for f_login_log.F_Login_Time
     *
     * @mbggenerated Mon Sep 14 15:06:50 CST 2020
     */
    public void setfLoginTime(Date fLoginTime) {
        this.fLoginTime = fLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_login_log.F_Ip_Address
     *
     * @return the value of f_login_log.F_Ip_Address
     *
     * @mbggenerated Mon Sep 14 15:06:50 CST 2020
     */
    public String getfIpAddress() {
        return fIpAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_login_log.F_Ip_Address
     *
     * @param fIpAddress the value for f_login_log.F_Ip_Address
     *
     * @mbggenerated Mon Sep 14 15:06:50 CST 2020
     */
    public void setfIpAddress(String fIpAddress) {
        this.fIpAddress = fIpAddress;
    }
}