package com.jyinfo.jy_domain.Entity.mybatisEntity;

import java.util.Date;

public class PositionApplyEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_position_apply.F_Apply_ID
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    private Integer fApplyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_position_apply.F_Employee_Name
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    private String fEmployeeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_position_apply.F_Recruition_Code
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    private Integer fRecruitionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_position_apply.F_Employee_CV
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    private String fEmployeeCv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_position_apply.F_Employee_Attach
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    private String fEmployeeAttach;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_position_apply.F_Employee_Mobile
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    private String fEmployeeMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_position_apply.F_Employee_Email
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    private String fEmployeeEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_position_apply.F_Create_Time
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    private Date fCreateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_position_apply.F_Apply_ID
     *
     * @return the value of t_position_apply.F_Apply_ID
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    public Integer getfApplyId() {
        return fApplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_position_apply.F_Apply_ID
     *
     * @param fApplyId the value for t_position_apply.F_Apply_ID
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    public void setfApplyId(Integer fApplyId) {
        this.fApplyId = fApplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_position_apply.F_Employee_Name
     *
     * @return the value of t_position_apply.F_Employee_Name
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    public String getfEmployeeName() {
        return fEmployeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_position_apply.F_Employee_Name
     *
     * @param fEmployeeName the value for t_position_apply.F_Employee_Name
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    public void setfEmployeeName(String fEmployeeName) {
        this.fEmployeeName = fEmployeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_position_apply.F_Recruition_Code
     *
     * @return the value of t_position_apply.F_Recruition_Code
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    public Integer getfRecruitionCode() {
        return fRecruitionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_position_apply.F_Recruition_Code
     *
     * @param fRecruitionCode the value for t_position_apply.F_Recruition_Code
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    public void setfRecruitionCode(Integer fRecruitionCode) {
        this.fRecruitionCode = fRecruitionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_position_apply.F_Employee_CV
     *
     * @return the value of t_position_apply.F_Employee_CV
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    public String getfEmployeeCv() {
        return fEmployeeCv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_position_apply.F_Employee_CV
     *
     * @param fEmployeeCv the value for t_position_apply.F_Employee_CV
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    public void setfEmployeeCv(String fEmployeeCv) {
        this.fEmployeeCv = fEmployeeCv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_position_apply.F_Employee_Attach
     *
     * @return the value of t_position_apply.F_Employee_Attach
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    public String getfEmployeeAttach() {
        return fEmployeeAttach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_position_apply.F_Employee_Attach
     *
     * @param fEmployeeAttach the value for t_position_apply.F_Employee_Attach
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    public void setfEmployeeAttach(String fEmployeeAttach) {
        this.fEmployeeAttach = fEmployeeAttach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_position_apply.F_Employee_Mobile
     *
     * @return the value of t_position_apply.F_Employee_Mobile
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    public String getfEmployeeMobile() {
        return fEmployeeMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_position_apply.F_Employee_Mobile
     *
     * @param fEmployeeMobile the value for t_position_apply.F_Employee_Mobile
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    public void setfEmployeeMobile(String fEmployeeMobile) {
        this.fEmployeeMobile = fEmployeeMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_position_apply.F_Employee_Email
     *
     * @return the value of t_position_apply.F_Employee_Email
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    public String getfEmployeeEmail() {
        return fEmployeeEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_position_apply.F_Employee_Email
     *
     * @param fEmployeeEmail the value for t_position_apply.F_Employee_Email
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    public void setfEmployeeEmail(String fEmployeeEmail) {
        this.fEmployeeEmail = fEmployeeEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_position_apply.F_Create_Time
     *
     * @return the value of t_position_apply.F_Create_Time
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    public Date getfCreateTime() {
        return fCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_position_apply.F_Create_Time
     *
     * @param fCreateTime the value for t_position_apply.F_Create_Time
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    public void setfCreateTime(Date fCreateTime) {
        this.fCreateTime = fCreateTime;
    }

    @Override
    public String toString() {
        return "PositionApplyEntity{" +
                "fApplyId=" + fApplyId +
                ", fEmployeeName='" + fEmployeeName + '\'' +
                ", fRecruitionCode=" + fRecruitionCode +
                ", fEmployeeCv='" + fEmployeeCv + '\'' +
                ", fEmployeeAttach='" + fEmployeeAttach + '\'' +
                ", fEmployeeMobile='" + fEmployeeMobile + '\'' +
                ", fEmployeeEmail='" + fEmployeeEmail + '\'' +
                ", fCreateTime=" + fCreateTime +
                '}';
    }
}