package com.jyinfo.jy_domain.Entity.mybatisEntity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PositionApplyEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_position_apply
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_position_apply
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_position_apply
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_apply
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    public PositionApplyEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_apply
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_apply
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_apply
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_apply
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_apply
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_apply
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_apply
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_apply
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_apply
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_apply
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_position_apply
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFApplyIdIsNull() {
            addCriterion("F_Apply_ID is null");
            return (Criteria) this;
        }

        public Criteria andFApplyIdIsNotNull() {
            addCriterion("F_Apply_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFApplyIdEqualTo(Integer value) {
            addCriterion("F_Apply_ID =", value, "fApplyId");
            return (Criteria) this;
        }

        public Criteria andFApplyIdNotEqualTo(Integer value) {
            addCriterion("F_Apply_ID <>", value, "fApplyId");
            return (Criteria) this;
        }

        public Criteria andFApplyIdGreaterThan(Integer value) {
            addCriterion("F_Apply_ID >", value, "fApplyId");
            return (Criteria) this;
        }

        public Criteria andFApplyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("F_Apply_ID >=", value, "fApplyId");
            return (Criteria) this;
        }

        public Criteria andFApplyIdLessThan(Integer value) {
            addCriterion("F_Apply_ID <", value, "fApplyId");
            return (Criteria) this;
        }

        public Criteria andFApplyIdLessThanOrEqualTo(Integer value) {
            addCriterion("F_Apply_ID <=", value, "fApplyId");
            return (Criteria) this;
        }

        public Criteria andFApplyIdIn(List<Integer> values) {
            addCriterion("F_Apply_ID in", values, "fApplyId");
            return (Criteria) this;
        }

        public Criteria andFApplyIdNotIn(List<Integer> values) {
            addCriterion("F_Apply_ID not in", values, "fApplyId");
            return (Criteria) this;
        }

        public Criteria andFApplyIdBetween(Integer value1, Integer value2) {
            addCriterion("F_Apply_ID between", value1, value2, "fApplyId");
            return (Criteria) this;
        }

        public Criteria andFApplyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("F_Apply_ID not between", value1, value2, "fApplyId");
            return (Criteria) this;
        }

        public Criteria andFEmployeeNameIsNull() {
            addCriterion("F_Employee_Name is null");
            return (Criteria) this;
        }

        public Criteria andFEmployeeNameIsNotNull() {
            addCriterion("F_Employee_Name is not null");
            return (Criteria) this;
        }

        public Criteria andFEmployeeNameEqualTo(String value) {
            addCriterion("F_Employee_Name =", value, "fEmployeeName");
            return (Criteria) this;
        }

        public Criteria andFEmployeeNameNotEqualTo(String value) {
            addCriterion("F_Employee_Name <>", value, "fEmployeeName");
            return (Criteria) this;
        }

        public Criteria andFEmployeeNameGreaterThan(String value) {
            addCriterion("F_Employee_Name >", value, "fEmployeeName");
            return (Criteria) this;
        }

        public Criteria andFEmployeeNameGreaterThanOrEqualTo(String value) {
            addCriterion("F_Employee_Name >=", value, "fEmployeeName");
            return (Criteria) this;
        }

        public Criteria andFEmployeeNameLessThan(String value) {
            addCriterion("F_Employee_Name <", value, "fEmployeeName");
            return (Criteria) this;
        }

        public Criteria andFEmployeeNameLessThanOrEqualTo(String value) {
            addCriterion("F_Employee_Name <=", value, "fEmployeeName");
            return (Criteria) this;
        }

        public Criteria andFEmployeeNameLike(String value) {
            addCriterion("F_Employee_Name like", value, "fEmployeeName");
            return (Criteria) this;
        }

        public Criteria andFEmployeeNameNotLike(String value) {
            addCriterion("F_Employee_Name not like", value, "fEmployeeName");
            return (Criteria) this;
        }

        public Criteria andFEmployeeNameIn(List<String> values) {
            addCriterion("F_Employee_Name in", values, "fEmployeeName");
            return (Criteria) this;
        }

        public Criteria andFEmployeeNameNotIn(List<String> values) {
            addCriterion("F_Employee_Name not in", values, "fEmployeeName");
            return (Criteria) this;
        }

        public Criteria andFEmployeeNameBetween(String value1, String value2) {
            addCriterion("F_Employee_Name between", value1, value2, "fEmployeeName");
            return (Criteria) this;
        }

        public Criteria andFEmployeeNameNotBetween(String value1, String value2) {
            addCriterion("F_Employee_Name not between", value1, value2, "fEmployeeName");
            return (Criteria) this;
        }

        public Criteria andFRecruitionCodeIsNull() {
            addCriterion("F_Recruition_Code is null");
            return (Criteria) this;
        }

        public Criteria andFRecruitionCodeIsNotNull() {
            addCriterion("F_Recruition_Code is not null");
            return (Criteria) this;
        }

        public Criteria andFRecruitionCodeEqualTo(Integer value) {
            addCriterion("F_Recruition_Code =", value, "fRecruitionCode");
            return (Criteria) this;
        }

        public Criteria andFRecruitionCodeNotEqualTo(Integer value) {
            addCriterion("F_Recruition_Code <>", value, "fRecruitionCode");
            return (Criteria) this;
        }

        public Criteria andFRecruitionCodeGreaterThan(Integer value) {
            addCriterion("F_Recruition_Code >", value, "fRecruitionCode");
            return (Criteria) this;
        }

        public Criteria andFRecruitionCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("F_Recruition_Code >=", value, "fRecruitionCode");
            return (Criteria) this;
        }

        public Criteria andFRecruitionCodeLessThan(Integer value) {
            addCriterion("F_Recruition_Code <", value, "fRecruitionCode");
            return (Criteria) this;
        }

        public Criteria andFRecruitionCodeLessThanOrEqualTo(Integer value) {
            addCriterion("F_Recruition_Code <=", value, "fRecruitionCode");
            return (Criteria) this;
        }

        public Criteria andFRecruitionCodeIn(List<Integer> values) {
            addCriterion("F_Recruition_Code in", values, "fRecruitionCode");
            return (Criteria) this;
        }

        public Criteria andFRecruitionCodeNotIn(List<Integer> values) {
            addCriterion("F_Recruition_Code not in", values, "fRecruitionCode");
            return (Criteria) this;
        }

        public Criteria andFRecruitionCodeBetween(Integer value1, Integer value2) {
            addCriterion("F_Recruition_Code between", value1, value2, "fRecruitionCode");
            return (Criteria) this;
        }

        public Criteria andFRecruitionCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("F_Recruition_Code not between", value1, value2, "fRecruitionCode");
            return (Criteria) this;
        }

        public Criteria andFEmployeeCvIsNull() {
            addCriterion("F_Employee_CV is null");
            return (Criteria) this;
        }

        public Criteria andFEmployeeCvIsNotNull() {
            addCriterion("F_Employee_CV is not null");
            return (Criteria) this;
        }

        public Criteria andFEmployeeCvEqualTo(String value) {
            addCriterion("F_Employee_CV =", value, "fEmployeeCv");
            return (Criteria) this;
        }

        public Criteria andFEmployeeCvNotEqualTo(String value) {
            addCriterion("F_Employee_CV <>", value, "fEmployeeCv");
            return (Criteria) this;
        }

        public Criteria andFEmployeeCvGreaterThan(String value) {
            addCriterion("F_Employee_CV >", value, "fEmployeeCv");
            return (Criteria) this;
        }

        public Criteria andFEmployeeCvGreaterThanOrEqualTo(String value) {
            addCriterion("F_Employee_CV >=", value, "fEmployeeCv");
            return (Criteria) this;
        }

        public Criteria andFEmployeeCvLessThan(String value) {
            addCriterion("F_Employee_CV <", value, "fEmployeeCv");
            return (Criteria) this;
        }

        public Criteria andFEmployeeCvLessThanOrEqualTo(String value) {
            addCriterion("F_Employee_CV <=", value, "fEmployeeCv");
            return (Criteria) this;
        }

        public Criteria andFEmployeeCvLike(String value) {
            addCriterion("F_Employee_CV like", value, "fEmployeeCv");
            return (Criteria) this;
        }

        public Criteria andFEmployeeCvNotLike(String value) {
            addCriterion("F_Employee_CV not like", value, "fEmployeeCv");
            return (Criteria) this;
        }

        public Criteria andFEmployeeCvIn(List<String> values) {
            addCriterion("F_Employee_CV in", values, "fEmployeeCv");
            return (Criteria) this;
        }

        public Criteria andFEmployeeCvNotIn(List<String> values) {
            addCriterion("F_Employee_CV not in", values, "fEmployeeCv");
            return (Criteria) this;
        }

        public Criteria andFEmployeeCvBetween(String value1, String value2) {
            addCriterion("F_Employee_CV between", value1, value2, "fEmployeeCv");
            return (Criteria) this;
        }

        public Criteria andFEmployeeCvNotBetween(String value1, String value2) {
            addCriterion("F_Employee_CV not between", value1, value2, "fEmployeeCv");
            return (Criteria) this;
        }

        public Criteria andFEmployeeAttachIsNull() {
            addCriterion("F_Employee_Attach is null");
            return (Criteria) this;
        }

        public Criteria andFEmployeeAttachIsNotNull() {
            addCriterion("F_Employee_Attach is not null");
            return (Criteria) this;
        }

        public Criteria andFEmployeeAttachEqualTo(String value) {
            addCriterion("F_Employee_Attach =", value, "fEmployeeAttach");
            return (Criteria) this;
        }

        public Criteria andFEmployeeAttachNotEqualTo(String value) {
            addCriterion("F_Employee_Attach <>", value, "fEmployeeAttach");
            return (Criteria) this;
        }

        public Criteria andFEmployeeAttachGreaterThan(String value) {
            addCriterion("F_Employee_Attach >", value, "fEmployeeAttach");
            return (Criteria) this;
        }

        public Criteria andFEmployeeAttachGreaterThanOrEqualTo(String value) {
            addCriterion("F_Employee_Attach >=", value, "fEmployeeAttach");
            return (Criteria) this;
        }

        public Criteria andFEmployeeAttachLessThan(String value) {
            addCriterion("F_Employee_Attach <", value, "fEmployeeAttach");
            return (Criteria) this;
        }

        public Criteria andFEmployeeAttachLessThanOrEqualTo(String value) {
            addCriterion("F_Employee_Attach <=", value, "fEmployeeAttach");
            return (Criteria) this;
        }

        public Criteria andFEmployeeAttachLike(String value) {
            addCriterion("F_Employee_Attach like", value, "fEmployeeAttach");
            return (Criteria) this;
        }

        public Criteria andFEmployeeAttachNotLike(String value) {
            addCriterion("F_Employee_Attach not like", value, "fEmployeeAttach");
            return (Criteria) this;
        }

        public Criteria andFEmployeeAttachIn(List<String> values) {
            addCriterion("F_Employee_Attach in", values, "fEmployeeAttach");
            return (Criteria) this;
        }

        public Criteria andFEmployeeAttachNotIn(List<String> values) {
            addCriterion("F_Employee_Attach not in", values, "fEmployeeAttach");
            return (Criteria) this;
        }

        public Criteria andFEmployeeAttachBetween(String value1, String value2) {
            addCriterion("F_Employee_Attach between", value1, value2, "fEmployeeAttach");
            return (Criteria) this;
        }

        public Criteria andFEmployeeAttachNotBetween(String value1, String value2) {
            addCriterion("F_Employee_Attach not between", value1, value2, "fEmployeeAttach");
            return (Criteria) this;
        }

        public Criteria andFEmployeeMobileIsNull() {
            addCriterion("F_Employee_Mobile is null");
            return (Criteria) this;
        }

        public Criteria andFEmployeeMobileIsNotNull() {
            addCriterion("F_Employee_Mobile is not null");
            return (Criteria) this;
        }

        public Criteria andFEmployeeMobileEqualTo(String value) {
            addCriterion("F_Employee_Mobile =", value, "fEmployeeMobile");
            return (Criteria) this;
        }

        public Criteria andFEmployeeMobileNotEqualTo(String value) {
            addCriterion("F_Employee_Mobile <>", value, "fEmployeeMobile");
            return (Criteria) this;
        }

        public Criteria andFEmployeeMobileGreaterThan(String value) {
            addCriterion("F_Employee_Mobile >", value, "fEmployeeMobile");
            return (Criteria) this;
        }

        public Criteria andFEmployeeMobileGreaterThanOrEqualTo(String value) {
            addCriterion("F_Employee_Mobile >=", value, "fEmployeeMobile");
            return (Criteria) this;
        }

        public Criteria andFEmployeeMobileLessThan(String value) {
            addCriterion("F_Employee_Mobile <", value, "fEmployeeMobile");
            return (Criteria) this;
        }

        public Criteria andFEmployeeMobileLessThanOrEqualTo(String value) {
            addCriterion("F_Employee_Mobile <=", value, "fEmployeeMobile");
            return (Criteria) this;
        }

        public Criteria andFEmployeeMobileLike(String value) {
            addCriterion("F_Employee_Mobile like", value, "fEmployeeMobile");
            return (Criteria) this;
        }

        public Criteria andFEmployeeMobileNotLike(String value) {
            addCriterion("F_Employee_Mobile not like", value, "fEmployeeMobile");
            return (Criteria) this;
        }

        public Criteria andFEmployeeMobileIn(List<String> values) {
            addCriterion("F_Employee_Mobile in", values, "fEmployeeMobile");
            return (Criteria) this;
        }

        public Criteria andFEmployeeMobileNotIn(List<String> values) {
            addCriterion("F_Employee_Mobile not in", values, "fEmployeeMobile");
            return (Criteria) this;
        }

        public Criteria andFEmployeeMobileBetween(String value1, String value2) {
            addCriterion("F_Employee_Mobile between", value1, value2, "fEmployeeMobile");
            return (Criteria) this;
        }

        public Criteria andFEmployeeMobileNotBetween(String value1, String value2) {
            addCriterion("F_Employee_Mobile not between", value1, value2, "fEmployeeMobile");
            return (Criteria) this;
        }

        public Criteria andFEmployeeEmailIsNull() {
            addCriterion("F_Employee_Email is null");
            return (Criteria) this;
        }

        public Criteria andFEmployeeEmailIsNotNull() {
            addCriterion("F_Employee_Email is not null");
            return (Criteria) this;
        }

        public Criteria andFEmployeeEmailEqualTo(String value) {
            addCriterion("F_Employee_Email =", value, "fEmployeeEmail");
            return (Criteria) this;
        }

        public Criteria andFEmployeeEmailNotEqualTo(String value) {
            addCriterion("F_Employee_Email <>", value, "fEmployeeEmail");
            return (Criteria) this;
        }

        public Criteria andFEmployeeEmailGreaterThan(String value) {
            addCriterion("F_Employee_Email >", value, "fEmployeeEmail");
            return (Criteria) this;
        }

        public Criteria andFEmployeeEmailGreaterThanOrEqualTo(String value) {
            addCriterion("F_Employee_Email >=", value, "fEmployeeEmail");
            return (Criteria) this;
        }

        public Criteria andFEmployeeEmailLessThan(String value) {
            addCriterion("F_Employee_Email <", value, "fEmployeeEmail");
            return (Criteria) this;
        }

        public Criteria andFEmployeeEmailLessThanOrEqualTo(String value) {
            addCriterion("F_Employee_Email <=", value, "fEmployeeEmail");
            return (Criteria) this;
        }

        public Criteria andFEmployeeEmailLike(String value) {
            addCriterion("F_Employee_Email like", value, "fEmployeeEmail");
            return (Criteria) this;
        }

        public Criteria andFEmployeeEmailNotLike(String value) {
            addCriterion("F_Employee_Email not like", value, "fEmployeeEmail");
            return (Criteria) this;
        }

        public Criteria andFEmployeeEmailIn(List<String> values) {
            addCriterion("F_Employee_Email in", values, "fEmployeeEmail");
            return (Criteria) this;
        }

        public Criteria andFEmployeeEmailNotIn(List<String> values) {
            addCriterion("F_Employee_Email not in", values, "fEmployeeEmail");
            return (Criteria) this;
        }

        public Criteria andFEmployeeEmailBetween(String value1, String value2) {
            addCriterion("F_Employee_Email between", value1, value2, "fEmployeeEmail");
            return (Criteria) this;
        }

        public Criteria andFEmployeeEmailNotBetween(String value1, String value2) {
            addCriterion("F_Employee_Email not between", value1, value2, "fEmployeeEmail");
            return (Criteria) this;
        }

        public Criteria andFCreateTimeIsNull() {
            addCriterion("F_Create_Time is null");
            return (Criteria) this;
        }

        public Criteria andFCreateTimeIsNotNull() {
            addCriterion("F_Create_Time is not null");
            return (Criteria) this;
        }

        public Criteria andFCreateTimeEqualTo(Date value) {
            addCriterion("F_Create_Time =", value, "fCreateTime");
            return (Criteria) this;
        }

        public Criteria andFCreateTimeNotEqualTo(Date value) {
            addCriterion("F_Create_Time <>", value, "fCreateTime");
            return (Criteria) this;
        }

        public Criteria andFCreateTimeGreaterThan(Date value) {
            addCriterion("F_Create_Time >", value, "fCreateTime");
            return (Criteria) this;
        }

        public Criteria andFCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("F_Create_Time >=", value, "fCreateTime");
            return (Criteria) this;
        }

        public Criteria andFCreateTimeLessThan(Date value) {
            addCriterion("F_Create_Time <", value, "fCreateTime");
            return (Criteria) this;
        }

        public Criteria andFCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("F_Create_Time <=", value, "fCreateTime");
            return (Criteria) this;
        }

        public Criteria andFCreateTimeIn(List<Date> values) {
            addCriterion("F_Create_Time in", values, "fCreateTime");
            return (Criteria) this;
        }

        public Criteria andFCreateTimeNotIn(List<Date> values) {
            addCriterion("F_Create_Time not in", values, "fCreateTime");
            return (Criteria) this;
        }

        public Criteria andFCreateTimeBetween(Date value1, Date value2) {
            addCriterion("F_Create_Time between", value1, value2, "fCreateTime");
            return (Criteria) this;
        }

        public Criteria andFCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("F_Create_Time not between", value1, value2, "fCreateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_position_apply
     *
     * @mbggenerated do_not_delete_during_merge Thu Sep 10 00:54:08 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_position_apply
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}