package com.jyinfo.jy_domain.Entity.mybatisEntity;

import java.util.Date;

public class UserEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.F_User_ID
     *
     * @mbggenerated Mon Sep 14 21:59:23 CST 2020
     */
    private Integer fUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.F_User_Name
     *
     * @mbggenerated Mon Sep 14 21:59:23 CST 2020
     */
    private String fUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.F_Profile
     *
     * @mbggenerated Mon Sep 14 21:59:23 CST 2020
     */
    private String fProfile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.F_User_Password
     *
     * @mbggenerated Mon Sep 14 21:59:23 CST 2020
     */
    private String fUserPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.F_Salt
     *
     * @mbggenerated Mon Sep 14 21:59:23 CST 2020
     */
    private String fSalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.F_Create_Time
     *
     * @mbggenerated Mon Sep 14 21:59:23 CST 2020
     */
    private Date fCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.F_Mobile
     *
     * @mbggenerated Mon Sep 14 21:59:23 CST 2020
     */
    private String fMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.F_Email
     *
     * @mbggenerated Mon Sep 14 21:59:23 CST 2020
     */
    private String fEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.F_Update_Time
     *
     * @mbggenerated Mon Sep 14 21:59:23 CST 2020
     */
    private Date fUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.F_User_ID
     *
     * @return the value of f_user.F_User_ID
     *
     * @mbggenerated Mon Sep 14 21:59:23 CST 2020
     */
    public Integer getfUserId() {
        return fUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.F_User_ID
     *
     * @param fUserId the value for f_user.F_User_ID
     *
     * @mbggenerated Mon Sep 14 21:59:23 CST 2020
     */
    public void setfUserId(Integer fUserId) {
        this.fUserId = fUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.F_User_Name
     *
     * @return the value of f_user.F_User_Name
     *
     * @mbggenerated Mon Sep 14 21:59:23 CST 2020
     */
    public String getfUserName() {
        return fUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.F_User_Name
     *
     * @param fUserName the value for f_user.F_User_Name
     *
     * @mbggenerated Mon Sep 14 21:59:23 CST 2020
     */
    public void setfUserName(String fUserName) {
        this.fUserName = fUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.F_Profile
     *
     * @return the value of f_user.F_Profile
     *
     * @mbggenerated Mon Sep 14 21:59:23 CST 2020
     */
    public String getfProfile() {
        return fProfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.F_Profile
     *
     * @param fProfile the value for f_user.F_Profile
     *
     * @mbggenerated Mon Sep 14 21:59:23 CST 2020
     */
    public void setfProfile(String fProfile) {
        this.fProfile = fProfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.F_User_Password
     *
     * @return the value of f_user.F_User_Password
     *
     * @mbggenerated Mon Sep 14 21:59:23 CST 2020
     */
    public String getfUserPassword() {
        return fUserPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.F_User_Password
     *
     * @param fUserPassword the value for f_user.F_User_Password
     *
     * @mbggenerated Mon Sep 14 21:59:23 CST 2020
     */
    public void setfUserPassword(String fUserPassword) {
        this.fUserPassword = fUserPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.F_Salt
     *
     * @return the value of f_user.F_Salt
     *
     * @mbggenerated Mon Sep 14 21:59:23 CST 2020
     */
    public String getfSalt() {
        return fSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.F_Salt
     *
     * @param fSalt the value for f_user.F_Salt
     *
     * @mbggenerated Mon Sep 14 21:59:23 CST 2020
     */
    public void setfSalt(String fSalt) {
        this.fSalt = fSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.F_Create_Time
     *
     * @return the value of f_user.F_Create_Time
     *
     * @mbggenerated Mon Sep 14 21:59:23 CST 2020
     */
    public Date getfCreateTime() {
        return fCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.F_Create_Time
     *
     * @param fCreateTime the value for f_user.F_Create_Time
     *
     * @mbggenerated Mon Sep 14 21:59:23 CST 2020
     */
    public void setfCreateTime(Date fCreateTime) {
        this.fCreateTime = fCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.F_Mobile
     *
     * @return the value of f_user.F_Mobile
     *
     * @mbggenerated Mon Sep 14 21:59:23 CST 2020
     */
    public String getfMobile() {
        return fMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.F_Mobile
     *
     * @param fMobile the value for f_user.F_Mobile
     *
     * @mbggenerated Mon Sep 14 21:59:23 CST 2020
     */
    public void setfMobile(String fMobile) {
        this.fMobile = fMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.F_Email
     *
     * @return the value of f_user.F_Email
     *
     * @mbggenerated Mon Sep 14 21:59:23 CST 2020
     */
    public String getfEmail() {
        return fEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.F_Email
     *
     * @param fEmail the value for f_user.F_Email
     *
     * @mbggenerated Mon Sep 14 21:59:23 CST 2020
     */
    public void setfEmail(String fEmail) {
        this.fEmail = fEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.F_Update_Time
     *
     * @return the value of f_user.F_Update_Time
     *
     * @mbggenerated Mon Sep 14 21:59:23 CST 2020
     */
    public Date getfUpdateTime() {
        return fUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.F_Update_Time
     *
     * @param fUpdateTime the value for f_user.F_Update_Time
     *
     * @mbggenerated Mon Sep 14 21:59:23 CST 2020
     */
    public void setfUpdateTime(Date fUpdateTime) {
        this.fUpdateTime = fUpdateTime;
    }
}