package com.jyinfo.jy_domain.mapper.mybatisMapper;

import java.io.Serializable;
import java.util.List;

import com.jyinfo.jy_domain.Entity.mybatisEntity.DevelopConsultEntity;
import com.jyinfo.jy_domain.Entity.mybatisEntity.DevelopConsultEntityExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface DevelopConsultEntityMapper extends Serializable {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_develop_consult
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    int countByExample(DevelopConsultEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_develop_consult
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    int deleteByExample(DevelopConsultEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_develop_consult
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    @Delete({
        "delete from t_develop_consult",
        "where F_Consult_ID = #{fConsultId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer fConsultId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_develop_consult
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    @Insert({
        "insert into t_develop_consult (F_Name, F_Mobile, ",
        "F_Unit, F_Budget, ",
        "F_Description, F_Create_Time)",
        "values (#{fName,jdbcType=VARCHAR}, #{fMobile,jdbcType=VARCHAR}, ",
        "#{fUnit,jdbcType=VARCHAR}, #{fBudget,jdbcType=VARCHAR}, ",
        "#{fDescription,jdbcType=VARCHAR}, #{fCreateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="fConsultId", before=false, resultType=Integer.class)
    int insert(DevelopConsultEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_develop_consult
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    int insertSelective(DevelopConsultEntity record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_develop_consult
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_develop_consult
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    int updateByExampleSelective(@Param("record") DevelopConsultEntity record, @Param("example") DevelopConsultEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_develop_consult
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    int updateByExample(@Param("record") DevelopConsultEntity record, @Param("example") DevelopConsultEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_develop_consult
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    int updateByPrimaryKeySelective(DevelopConsultEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_develop_consult
     *
     * @mbggenerated Thu Sep 10 01:08:19 CST 2020
     */
    @Update({
        "update t_develop_consult",
        "set F_Name = #{fName,jdbcType=VARCHAR},",
          "F_Mobile = #{fMobile,jdbcType=VARCHAR},",
          "F_Unit = #{fUnit,jdbcType=VARCHAR},",
          "F_Budget = #{fBudget,jdbcType=VARCHAR},",
          "F_Description = #{fDescription,jdbcType=VARCHAR},",
          "F_Create_Time = #{fCreateTime,jdbcType=TIMESTAMP}",
        "where F_Consult_ID = #{fConsultId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(DevelopConsultEntity record);
}