package com.jyinfo.jy_domain.mapper.mybatisMapper;

import java.io.Serializable;
import java.util.List;

import com.jyinfo.jy_domain.Entity.mybatisEntity.LoginLogEntity;
import com.jyinfo.jy_domain.Entity.mybatisEntity.LoginLogEntityExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface LoginLogEntityMapper extends Serializable {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_login_log
     *
     * @mbggenerated Mon Sep 14 15:06:50 CST 2020
     */
    int countByExample(LoginLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_login_log
     *
     * @mbggenerated Mon Sep 14 15:06:50 CST 2020
     */
    int deleteByExample(LoginLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_login_log
     *
     * @mbggenerated Mon Sep 14 15:06:50 CST 2020
     */
    @Delete({
        "delete from f_login_log",
        "where F_Log_Id = #{fLogId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer fLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_login_log
     *
     * @mbggenerated Mon Sep 14 15:06:50 CST 2020
     */
    @Insert({
        "insert into f_login_log (F_User_ID, F_Login_Time, ",
        "F_Ip_Address)",
        "values (#{fUserId,jdbcType=INTEGER}, #{fLoginTime,jdbcType=TIMESTAMP}, ",
        "#{fIpAddress,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="fLogId", before=false, resultType=Integer.class)
    int insert(LoginLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_login_log
     *
     * @mbggenerated Mon Sep 14 15:06:50 CST 2020
     */
    int insertSelective(LoginLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_login_log
     *
     * @mbggenerated Mon Sep 14 15:06:50 CST 2020
     */
    List<LoginLogEntity> selectByExample(LoginLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_login_log
     *
     * @mbggenerated Mon Sep 14 15:06:50 CST 2020
     */
    @Select({
        "select",
        "F_Log_Id, F_User_ID, F_Login_Time, F_Ip_Address",
        "from f_login_log",
        "where F_Log_Id = #{fLogId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    LoginLogEntity selectByPrimaryKey(Integer fLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_login_log
     *
     * @mbggenerated Mon Sep 14 15:06:50 CST 2020
     */
    int updateByExampleSelective(@Param("record") LoginLogEntity record, @Param("example") LoginLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_login_log
     *
     * @mbggenerated Mon Sep 14 15:06:50 CST 2020
     */
    int updateByExample(@Param("record") LoginLogEntity record, @Param("example") LoginLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_login_log
     *
     * @mbggenerated Mon Sep 14 15:06:50 CST 2020
     */
    int updateByPrimaryKeySelective(LoginLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_login_log
     *
     * @mbggenerated Mon Sep 14 15:06:50 CST 2020
     */
    @Update({
        "update f_login_log",
        "set F_User_ID = #{fUserId,jdbcType=INTEGER},",
          "F_Login_Time = #{fLoginTime,jdbcType=TIMESTAMP},",
          "F_Ip_Address = #{fIpAddress,jdbcType=VARCHAR}",
        "where F_Log_Id = #{fLogId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(LoginLogEntity record);
}