package com.jyinfo.jy_domain.mapper.mybatisMapper;

import java.io.Serializable;
import java.util.List;

import com.jyinfo.jy_domain.Entity.mybatisEntity.PositionApplyEntity;
import com.jyinfo.jy_domain.Entity.mybatisEntity.PositionApplyEntityExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface PositionApplyEntityMapper extends Serializable {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_apply
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    int countByExample(PositionApplyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_apply
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    int deleteByExample(PositionApplyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_apply
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    @Delete({
        "delete from t_position_apply",
        "where F_Apply_ID = #{fApplyId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer fApplyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_apply
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    @Insert({
        "insert into t_position_apply (F_Employee_Name, F_Recruition_Code, ",
        "F_Employee_CV, F_Employee_Attach, ",
        "F_Employee_Mobile, F_Employee_Email, ",
        "F_Create_Time)",
        "values (#{fEmployeeName,jdbcType=VARCHAR}, #{fRecruitionCode,jdbcType=INTEGER}, ",
        "#{fEmployeeCv,jdbcType=VARCHAR}, #{fEmployeeAttach,jdbcType=VARCHAR}, ",
        "#{fEmployeeMobile,jdbcType=VARCHAR}, #{fEmployeeEmail,jdbcType=VARCHAR}, ",
        "#{fCreateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="fApplyId", before=false, resultType=Integer.class)
    int insert(PositionApplyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_apply
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    int insertSelective(PositionApplyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_apply
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    List<PositionApplyEntity> selectByExample(PositionApplyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_apply
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_apply
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    int updateByExampleSelective(@Param("record") PositionApplyEntity record, @Param("example") PositionApplyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_apply
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    int updateByExample(@Param("record") PositionApplyEntity record, @Param("example") PositionApplyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_apply
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    int updateByPrimaryKeySelective(PositionApplyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_apply
     *
     * @mbggenerated Thu Sep 10 00:54:08 CST 2020
     */
    @Update({
        "update t_position_apply",
        "set F_Employee_Name = #{fEmployeeName,jdbcType=VARCHAR},",
          "F_Recruition_Code = #{fRecruitionCode,jdbcType=INTEGER},",
          "F_Employee_CV = #{fEmployeeCv,jdbcType=VARCHAR},",
          "F_Employee_Attach = #{fEmployeeAttach,jdbcType=VARCHAR},",
          "F_Employee_Mobile = #{fEmployeeMobile,jdbcType=VARCHAR},",
          "F_Employee_Email = #{fEmployeeEmail,jdbcType=VARCHAR},",
          "F_Create_Time = #{fCreateTime,jdbcType=TIMESTAMP}",
        "where F_Apply_ID = #{fApplyId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PositionApplyEntity record);
}